# Generated by Django 5.0.4 on 2024-04-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        # Alter the table name of the Property model to 'properties'
        migrations.AlterModelTable(
            name='property',
            table='properties',
        ),
    ]
